(function() {

  var app = angular.module("characterViewer", []);

  var MainController = function($scope, $http) {


    var onUserComplete = function(response) {
      $scope.characterData = response.data;
      $scope.statsKeys = Object.keys($scope.characterData.stats);
    };

    var onError = function(ex) {
      $scope.error = "Could not fetch character";
    };

    $scope.getCharacterData = function() {

      var characterName = $scope.name;
      var serverName = $scope.server;

      $http.get("https://us.api.battle.net/wow/character/" + serverName + "/" +
          characterName + "?fields=stats&locale=en_US&apikey=wx99z97834buae5egsqr6vgmwejmdgap")
        .then(onUserComplete, onError);

    };

    function getArtifactData() {
      var characterRequest = new XMLHttpRequest();

      var characterName = document.getElementsByName("name")[0].value;
      var serverName = document.getElementsByName("server")[0].value;

      characterRequest.open("GET", "https://us.api.battle.net/wow/character/" + serverName + "/" + characterName + "?fields=items&locale=en_US&apikey=wx99z97834buae5egsqr6vgmwejmdgap", true);
      characterRequest.send();

      characterRequest.onload = function() {
        artifactData = characterRequest.response["items"]["mainHand"];

        document.getElementById("artifact").appendChild(
          document.createElement("ul")
        );
      };

    }

    $scope.name = "Lustily";
    $scope.server = "Dalaran";

  };

  app.controller("MainController", ["$scope", "$http", MainController]);

}());
//TODO: dropdown generated by profile fields to select and view values